---
- name: Prepare Developement Setup
  hosts: localhost
  vars_files:
    - vars.yml

  roles:
    - role: veerendra2.prepare_dev_setup
    - role: geerlingguy.docker
      when: ansible_system == "Linux"
