# Author: Veerendra Kakumanu
# Description: An Ansible playbook to install packages

- name: Prepare Ubuntu
  hosts: localhost
  gather_facts: yes
  vars_files:
    - vars.yml
    #- vault.yml

  pre_tasks:
    - name: Run Update
      apt:
        upgrade: yes
        update_cache: yes
      ignore_errors: yes
      become: yes

  post_tasks:
    - name: Run autoremove
      apt:
        autoclean: yes
        autoremove: yes
      ignore_errors: yes
      become: yes

  tasks:
    - import_tasks: tasks/cli-tools.yml
      tags: cli
    - import_tasks: tasks/desktop.yml
      tags: desktop
