# Author: Veerendra Kakumanu
# Description: An Ansible playbook to install packages

- name: Init My Machine
  hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - vars.yml

  pre_tasks:
    - name: Run Update
      apt:
        upgrade: yes
        update_cache: yes
      ignore_errors: yes
      become: yes

  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/cli-tools.yml
    - import_tasks: tasks/desktop.yml
