# Author: Veerendra Kakumanu
# Description: An Ansible playbook to install packages

- name: Init My Machine
  hosts: localhost
  connection: local
  gather_facts: yes
  vars_files:
    - pkgs_vars.yml

  tasks:
  - name: Run Update
    apt:
      upgrade: yes
      update_cache: yes
    ignore_errors: yes
    become: yes

  - name: Adding PPAs
    apt_repository:
      repo: "{{ item.value }}"
      state: present
      update_cache: no
    loop: "{{ lookup('dict', pkgs_ppa, wantlist=True) }}"
    loop_control:
      label: "{{ item.key }}"
    become: yes
    tags: ["gen"]

  - debug: msg="{{ pkgs_key }}"

  - name: Add Repo Keys
    apt_key:
      url: "{{ item.value }}"
      state: present
    loop: "{{ lookup('dict', pkgs_key, wantlist=True) }}"
    loop_control:
      label: "{{ item.key }}"
    become: yes
    tags: ["gen"]

  - name: Install General Packges
    apt:
      name: "{{ gen_pkgs }}"
      state: installed
      update_cache: yes
    become: yes
    tags: ["gen"]

  - name: Install Dev Packges
    apt:
      name: "{{ dev_pkgs }}"
      state: installed
      update_cache: yes
    become: yes
    tags: ["dev"]

  - name: Install Python Packges
    pip:
      name: "{{ pip_pkgs }}"
    become: yes
    tags: ["pip"]

  - name: Download Tools
    get_url:
      url: "{{ item.value }}"
      dest: "{{ item.key }}"
      mode: '0111'
    loop: "{{ lookup('dict', tools) }}"
    tags: ["tools"]

  - name: Cloning repo
    git:
      repo: "{{ item.value }}"
      dest: "{{lookup('env','HOME')}}/{{ item.key }}"
    loop: "{{ lookup('dict', git_projects) }}"
    tags: ["repo"]

  - name: Add DockerRepo
    apt_repository:
      repo: "{{ docker['repo'] }}"
      state: present
    become: yes
    tags: ["docker"]

  - name: Add Docker Key
    apt_key:
      url: "{{ docker['key'] }}"
      state: present
    become: yes
    tags: ["docker"]

  - name: Install docker
    apt:
      name: 
        - "docker-ce"
        - "docker-ce-cli" 
        - "containerd.io"
    become: yes
    tags: ["docker"]

  
    
      
  

  
    
